INSERT INTO
  albums (title, artist)
VALUES
  ('Malibu', 'Anderson .Paak'),
  ('A Seat at the Table', 'Solange Knowles'),
  ('Melodrama', 'Lorde'),
  ('In Rainbows', 'Radiohead')
;

INSERT INTO
  users (name, email, password)
VALUES
  ('Homer Simpson', 'homer@gmail.com', 'homer'),
  ('Marge Simpson', 'marge@gmail.com', 'marge'),
  ('Bart Simpson', 'bart@gmail.com', 'bart'),
  ('Lisa Simpson', 'lisa@gmail.com', 'lisa'),
  ('Maggie Simpson', 'maggie@gmail.com', 'maggie')
;

INSERT INTO
  reviews (content, author_id, album_id)
VALUES
  ('Lorem Khaled Ipsum is a major key to success. Always remember in the jungle there’’s a lot of they in there, after you overcome they, you will make it to paradise. The key is to enjoy life, because they don’’t want you to enjoy life. I promise you, they don’’t want you to jetski, they don’’t want you to smile. How’’s business? Boomin. It’’s important to use cocoa butter. It’’s the key to more success, why not live smooth? Why live rough? They key is to have every key, the key to open every door.   We don’’t see them, we will never see them.

  Every chance I get, I water the plants, Lion! The key to success is to keep your head above the water, never give up. Fan luv. In life you have to take the trash out, if you have trash in your life, take it out, throw it away, get rid of it, major key. They don’’t want us to eat. Give thanks to the most high. Surround yourself with angels, positive energy, beautiful people, beautiful souls, clean heart, angel. You do know, you do know that they don’’t want you to have lunch. I’’m keeping it real with you, so what you going do is have lunch.', 1, 1),
  ('Don’’t ever play yourself. You should never complain, complaining is a weak emotion, you got life, we breathing, we blessed. The key to more success is to get a massage once a week, very important, major key, cloth talk. Major key, don’’t fall for the trap, stay focused. It’’s the ones closest to you that want to see you fail. In life there will be road blocks but we will over come it. Put it this way, it took me twenty five years to get these plants, twenty five years of blood sweat and tears, and I’’m never giving up, I’’m just getting started.

  They don’’t want us to eat. Look at the sunset, life is amazing, life is beautiful, life is what you make it. Watch your back, but more importantly when you get out the shower, dry your back, it’’s a cold world out there. I’’m giving you cloth talk, cloth. Special cloth alert, cut from a special cloth. You smart, you loyal, you a genius. To succeed you must believe. When you believe, you will succeed. They will try to close the door on you, just open it. It’’s important to use cocoa butter. It’’s the key to more success, why not live smooth? Why live rough?

  They never said winning was easy. Some people can’’t handle success, I can. The key to success is to keep your head above the water, never give up. Hammock talk come soon. It’’s on you how you want to live your life. Everyone has a choice. I pick my choice, squeaky clean. The ladies always say Khaled you smell good, I use no cologne. Cocoa butter is the key. Learning is cool, but knowing is better, and I know the key to success. The ladies always say Khaled you smell good, I use no cologne. Cocoa butter is the key. Mogul talk.', 1, 2),
  ('Egg whites, turkey sausage, wheat toast, water. Of course they don’’t want us to eat our breakfast, so we are going to enjoy our breakfast. Hammock talk come soon. To succeed you must believe. When you believe, you will succeed. The weather is amazing, walk with me through the pathway of more success. Take this journey with me, Lion! A major key, never panic. Don’’t panic, when it gets crazy and rough, don’’t panic, stay calm. Hammock talk come soon. Let me be clear, you have to make it through the jungle to make it to paradise, that’’s the key, Lion!', 1, 3),
  ('In life you have to take the trash out, if you have trash in your life, take it out, throw it away, get rid of it, major key. To be successful you’’ve got to work hard, to make history, simple, you’’ve got to make it. Wraith talk. The other day the grass was brown, now it’’s green because I ain’’t give up. Never surrender. I’’m giving you cloth talk, cloth. Special cloth alert, cut from a special cloth. I’’m giving you cloth talk, cloth. Special cloth alert, cut from a special cloth.

  The ladies always say Khaled you smell good, I use no cologne. Cocoa butter is the key. The ladies always say Khaled you smell good, I use no cologne. Cocoa butter is the key. It’’s on you how you want to live your life. Everyone has a choice. I pick my choice, squeaky clean. The key to success is to keep your head above the water, never give up. Lion! I’’m giving you cloth talk, cloth. Special cloth alert, cut from a special cloth. Egg whites, turkey sausage, wheat toast, water. Of course they don’’t want us to eat our breakfast, so we are going to enjoy our breakfast.

  Congratulations, you played yourself. I’’m up to something. Congratulations, you played yourself. In life there will be road blocks but we will over come it. You see that bamboo behind me though, you see that bamboo? Ain’’t nothin’’ like bamboo. Bless up. The key is to drink coconut, fresh coconut, trust me. Hammock talk come soon. How’’s business? Boomin. Another one. We don’’t see them, we will never see them. Give thanks to the most high. Lion!

  In life you have to take the trash out, if you have trash in your life, take it out, throw it away, get rid of it, major key. The key is to enjoy life, because they don’’t want you to enjoy life. I promise you, they don’’t want you to jetski, they don’’t want you to smile. Surround yourself with angels. Surround yourself with angels. Celebrate success right, the only way, apple. Always remember in the jungle there’’s a lot of they in there, after you overcome they, you will make it to paradise. The other day the grass was brown, now it’’s green because I ain’’t give up. Never surrender.

  To be successful you’’ve got to work hard, to make history, simple, you’’ve got to make it. Always remember in the jungle there’’s a lot of they in there, after you overcome they, you will make it to paradise. It’’s on you how you want to live your life. Everyone has a choice. I pick my choice, squeaky clean. In life there will be road blocks but we will over come it. Look at the sunset, life is amazing, life is beautiful, life is what you make it. The key is to drink coconut, fresh coconut, trust me.', 1, 4),
  ('Lorem Khaled Ipsum is a major key to success. Always remember in the jungle there’’s a lot of they in there, after you overcome they, you will make it to paradise. The key is to enjoy life, because they don’’t want you to enjoy life. I promise you, they don’’t want you to jetski, they don’’t want you to smile. How’’s business? Boomin. It’’s important to use cocoa butter. It’’s the key to more success, why not live smooth? Why live rough? They key is to have every key, the key to open every door.   We don’’t see them, we will never see them.

  Every chance I get, I water the plants, Lion! The key to success is to keep your head above the water, never give up. Fan luv. In life you have to take the trash out, if you have trash in your life, take it out, throw it away, get rid of it, major key. They don’’t want us to eat. Give thanks to the most high. Surround yourself with angels, positive energy, beautiful people, beautiful souls, clean heart, angel. You do know, you do know that they don’’t want you to have lunch. I’’m keeping it real with you, so what you going do is have lunch.', 2, 4),
  ('Don’’t ever play yourself. You should never complain, complaining is a weak emotion, you got life, we breathing, we blessed. The key to more success is to get a massage once a week, very important, major key, cloth talk. Major key, don’’t fall for the trap, stay focused. It’’s the ones closest to you that want to see you fail. In life there will be road blocks but we will over come it. Put it this way, it took me twenty five years to get these plants, twenty five years of blood sweat and tears, and I’’m never giving up, I’’m just getting started.

  They don’’t want us to eat. Look at the sunset, life is amazing, life is beautiful, life is what you make it. Watch your back, but more importantly when you get out the shower, dry your back, it’’s a cold world out there. I’’m giving you cloth talk, cloth. Special cloth alert, cut from a special cloth. You smart, you loyal, you a genius. To succeed you must believe. When you believe, you will succeed. They will try to close the door on you, just open it. It’’s important to use cocoa butter. It’’s the key to more success, why not live smooth? Why live rough?

  They never said winning was easy. Some people can’’t handle success, I can. The key to success is to keep your head above the water, never give up. Hammock talk come soon. It’’s on you how you want to live your life. Everyone has a choice. I pick my choice, squeaky clean. The ladies always say Khaled you smell good, I use no cologne. Cocoa butter is the key. Learning is cool, but knowing is better, and I know the key to success. The ladies always say Khaled you smell good, I use no cologne. Cocoa butter is the key. Mogul talk.', 2, 3),
  ('Egg whites, turkey sausage, wheat toast, water. Of course they don’’t want us to eat our breakfast, so we are going to enjoy our breakfast. Hammock talk come soon. To succeed you must believe. When you believe, you will succeed. The weather is amazing, walk with me through the pathway of more success. Take this journey with me, Lion! A major key, never panic. Don’’t panic, when it gets crazy and rough, don’’t panic, stay calm. Hammock talk come soon. Let me be clear, you have to make it through the jungle to make it to paradise, that’’s the key, Lion!', 2, 2),
  ('In life you have to take the trash out, if you have trash in your life, take it out, throw it away, get rid of it, major key. To be successful you’’ve got to work hard, to make history, simple, you’’ve got to make it. Wraith talk. The other day the grass was brown, now it’’s green because I ain’’t give up. Never surrender. I’’m giving you cloth talk, cloth. Special cloth alert, cut from a special cloth. I’’m giving you cloth talk, cloth. Special cloth alert, cut from a special cloth.

  The ladies always say Khaled you smell good, I use no cologne. Cocoa butter is the key. The ladies always say Khaled you smell good, I use no cologne. Cocoa butter is the key. It’’s on you how you want to live your life. Everyone has a choice. I pick my choice, squeaky clean. The key to success is to keep your head above the water, never give up. Lion! I’’m giving you cloth talk, cloth. Special cloth alert, cut from a special cloth. Egg whites, turkey sausage, wheat toast, water. Of course they don’’t want us to eat our breakfast, so we are going to enjoy our breakfast.

  Congratulations, you played yourself. I’’m up to something. Congratulations, you played yourself. In life there will be road blocks but we will over come it. You see that bamboo behind me though, you see that bamboo? Ain’’t nothin’’ like bamboo. Bless up. The key is to drink coconut, fresh coconut, trust me. Hammock talk come soon. How’’s business? Boomin. Another one. We don’’t see them, we will never see them. Give thanks to the most high. Lion!

  In life you have to take the trash out, if you have trash in your life, take it out, throw it away, get rid of it, major key. The key is to enjoy life, because they don’’t want you to enjoy life. I promise you, they don’’t want you to jetski, they don’’t want you to smile. Surround yourself with angels. Surround yourself with angels. Celebrate success right, the only way, apple. Always remember in the jungle there’’s a lot of they in there, after you overcome they, you will make it to paradise. The other day the grass was brown, now it’’s green because I ain’’t give up. Never surrender.

  To be successful you’’ve got to work hard, to make history, simple, you’’ve got to make it. Always remember in the jungle there’’s a lot of they in there, after you overcome they, you will make it to paradise. It’’s on you how you want to live your life. Everyone has a choice. I pick my choice, squeaky clean. In life there will be road blocks but we will over come it. Look at the sunset, life is amazing, life is beautiful, life is what you make it. The key is to drink coconut, fresh coconut, trust me.', 2, 1),
  ('Lorem Khaled Ipsum is a major key to success. Always remember in the jungle there’’s a lot of they in there, after you overcome they, you will make it to paradise. The key is to enjoy life, because they don’’t want you to enjoy life. I promise you, they don’’t want you to jetski, they don’’t want you to smile. How’’s business? Boomin. It’’s important to use cocoa butter. It’’s the key to more success, why not live smooth? Why live rough? They key is to have every key, the key to open every door.   We don’’t see them, we will never see them.

  Every chance I get, I water the plants, Lion! The key to success is to keep your head above the water, never give up. Fan luv. In life you have to take the trash out, if you have trash in your life, take it out, throw it away, get rid of it, major key. They don’’t want us to eat. Give thanks to the most high. Surround yourself with angels, positive energy, beautiful people, beautiful souls, clean heart, angel. You do know, you do know that they don’’t want you to have lunch. I’’m keeping it real with you, so what you going do is have lunch.', 3, 2),
  ('Don’’t ever play yourself. You should never complain, complaining is a weak emotion, you got life, we breathing, we blessed. The key to more success is to get a massage once a week, very important, major key, cloth talk. Major key, don’’t fall for the trap, stay focused. It’’s the ones closest to you that want to see you fail. In life there will be road blocks but we will over come it. Put it this way, it took me twenty five years to get these plants, twenty five years of blood sweat and tears, and I’’m never giving up, I’’m just getting started.

  They don’’t want us to eat. Look at the sunset, life is amazing, life is beautiful, life is what you make it. Watch your back, but more importantly when you get out the shower, dry your back, it’’s a cold world out there. I’’m giving you cloth talk, cloth. Special cloth alert, cut from a special cloth. You smart, you loyal, you a genius. To succeed you must believe. When you believe, you will succeed. They will try to close the door on you, just open it. It’’s important to use cocoa butter. It’’s the key to more success, why not live smooth? Why live rough?

  They never said winning was easy. Some people can’’t handle success, I can. The key to success is to keep your head above the water, never give up. Hammock talk come soon. It’’s on you how you want to live your life. Everyone has a choice. I pick my choice, squeaky clean. The ladies always say Khaled you smell good, I use no cologne. Cocoa butter is the key. Learning is cool, but knowing is better, and I know the key to success. The ladies always say Khaled you smell good, I use no cologne. Cocoa butter is the key. Mogul talk.', 3, 4),
  ('Egg whites, turkey sausage, wheat toast, water. Of course they don’’t want us to eat our breakfast, so we are going to enjoy our breakfast. Hammock talk come soon. To succeed you must believe. When you believe, you will succeed. The weather is amazing, walk with me through the pathway of more success. Take this journey with me, Lion! A major key, never panic. Don’’t panic, when it gets crazy and rough, don’’t panic, stay calm. Hammock talk come soon. Let me be clear, you have to make it through the jungle to make it to paradise, that’’s the key, Lion!', 3, 1),
  ('In life you have to take the trash out, if you have trash in your life, take it out, throw it away, get rid of it, major key. To be successful you’’ve got to work hard, to make history, simple, you’’ve got to make it. Wraith talk. The other day the grass was brown, now it’’s green because I ain’’t give up. Never surrender. I’’m giving you cloth talk, cloth. Special cloth alert, cut from a special cloth. I’’m giving you cloth talk, cloth. Special cloth alert, cut from a special cloth.

  The ladies always say Khaled you smell good, I use no cologne. Cocoa butter is the key. The ladies always say Khaled you smell good, I use no cologne. Cocoa butter is the key. It’’s on you how you want to live your life. Everyone has a choice. I pick my choice, squeaky clean. The key to success is to keep your head above the water, never give up. Lion! I’’m giving you cloth talk, cloth. Special cloth alert, cut from a special cloth. Egg whites, turkey sausage, wheat toast, water. Of course they don’’t want us to eat our breakfast, so we are going to enjoy our breakfast.

  Congratulations, you played yourself. I’’m up to something. Congratulations, you played yourself. In life there will be road blocks but we will over come it. You see that bamboo behind me though, you see that bamboo? Ain’’t nothin’’ like bamboo. Bless up. The key is to drink coconut, fresh coconut, trust me. Hammock talk come soon. How’’s business? Boomin. Another one. We don’’t see them, we will never see them. Give thanks to the most high. Lion!

  In life you have to take the trash out, if you have trash in your life, take it out, throw it away, get rid of it, major key. The key is to enjoy life, because they don’’t want you to enjoy life. I promise you, they don’’t want you to jetski, they don’’t want you to smile. Surround yourself with angels. Surround yourself with angels. Celebrate success right, the only way, apple. Always remember in the jungle there’’s a lot of they in there, after you overcome they, you will make it to paradise. The other day the grass was brown, now it’’s green because I ain’’t give up. Never surrender.

  To be successful you’’ve got to work hard, to make history, simple, you’’ve got to make it. Always remember in the jungle there’’s a lot of they in there, after you overcome they, you will make it to paradise. It’’s on you how you want to live your life. Everyone has a choice. I pick my choice, squeaky clean. In life there will be road blocks but we will over come it. Look at the sunset, life is amazing, life is beautiful, life is what you make it. The key is to drink coconut, fresh coconut, trust me.', 3, 3),
  ('Lorem Khaled Ipsum is a major key to success. Always remember in the jungle there’’s a lot of they in there, after you overcome they, you will make it to paradise. The key is to enjoy life, because they don’’t want you to enjoy life. I promise you, they don’’t want you to jetski, they don’’t want you to smile. How’’s business? Boomin. It’’s important to use cocoa butter. It’’s the key to more success, why not live smooth? Why live rough? They key is to have every key, the key to open every door.   We don’’t see them, we will never see them.

  Every chance I get, I water the plants, Lion! The key to success is to keep your head above the water, never give up. Fan luv. In life you have to take the trash out, if you have trash in your life, take it out, throw it away, get rid of it, major key. They don’’t want us to eat. Give thanks to the most high. Surround yourself with angels, positive energy, beautiful people, beautiful souls, clean heart, angel. You do know, you do know that they don’’t want you to have lunch. I’’m keeping it real with you, so what you going do is have lunch.', 4, 3),
  ('Don’’t ever play yourself. You should never complain, complaining is a weak emotion, you got life, we breathing, we blessed. The key to more success is to get a massage once a week, very important, major key, cloth talk. Major key, don’’t fall for the trap, stay focused. It’’s the ones closest to you that want to see you fail. In life there will be road blocks but we will over come it. Put it this way, it took me twenty five years to get these plants, twenty five years of blood sweat and tears, and I’’m never giving up, I’’m just getting started.

  They don’’t want us to eat. Look at the sunset, life is amazing, life is beautiful, life is what you make it. Watch your back, but more importantly when you get out the shower, dry your back, it’’s a cold world out there. I’’m giving you cloth talk, cloth. Special cloth alert, cut from a special cloth. You smart, you loyal, you a genius. To succeed you must believe. When you believe, you will succeed. They will try to close the door on you, just open it. It’’s important to use cocoa butter. It’’s the key to more success, why not live smooth? Why live rough?

  They never said winning was easy. Some people can’’t handle success, I can. The key to success is to keep your head above the water, never give up. Hammock talk come soon. It’’s on you how you want to live your life. Everyone has a choice. I pick my choice, squeaky clean. The ladies always say Khaled you smell good, I use no cologne. Cocoa butter is the key. Learning is cool, but knowing is better, and I know the key to success. The ladies always say Khaled you smell good, I use no cologne. Cocoa butter is the key. Mogul talk.', 4, 4),
  ('Egg whites, turkey sausage, wheat toast, water. Of course they don’’t want us to eat our breakfast, so we are going to enjoy our breakfast. Hammock talk come soon. To succeed you must believe. When you believe, you will succeed. The weather is amazing, walk with me through the pathway of more success. Take this journey with me, Lion! A major key, never panic. Don’’t panic, when it gets crazy and rough, don’’t panic, stay calm. Hammock talk come soon. Let me be clear, you have to make it through the jungle to make it to paradise, that’’s the key, Lion!', 4, 1),
  ('In life you have to take the trash out, if you have trash in your life, take it out, throw it away, get rid of it, major key. To be successful you’’ve got to work hard, to make history, simple, you’’ve got to make it. Wraith talk. The other day the grass was brown, now it’’s green because I ain’’t give up. Never surrender. I’’m giving you cloth talk, cloth. Special cloth alert, cut from a special cloth. I’’m giving you cloth talk, cloth. Special cloth alert, cut from a special cloth.

  The ladies always say Khaled you smell good, I use no cologne. Cocoa butter is the key. The ladies always say Khaled you smell good, I use no cologne. Cocoa butter is the key. It’’s on you how you want to live your life. Everyone has a choice. I pick my choice, squeaky clean. The key to success is to keep your head above the water, never give up. Lion! I’’m giving you cloth talk, cloth. Special cloth alert, cut from a special cloth. Egg whites, turkey sausage, wheat toast, water. Of course they don’’t want us to eat our breakfast, so we are going to enjoy our breakfast.

  Congratulations, you played yourself. I’’m up to something. Congratulations, you played yourself. In life there will be road blocks but we will over come it. You see that bamboo behind me though, you see that bamboo? Ain’’t nothin’’ like bamboo. Bless up. The key is to drink coconut, fresh coconut, trust me. Hammock talk come soon. How’’s business? Boomin. Another one. We don’’t see them, we will never see them. Give thanks to the most high. Lion!

  In life you have to take the trash out, if you have trash in your life, take it out, throw it away, get rid of it, major key. The key is to enjoy life, because they don’’t want you to enjoy life. I promise you, they don’’t want you to jetski, they don’’t want you to smile. Surround yourself with angels. Surround yourself with angels. Celebrate success right, the only way, apple. Always remember in the jungle there’’s a lot of they in there, after you overcome they, you will make it to paradise. The other day the grass was brown, now it’’s green because I ain’’t give up. Never surrender.

  To be successful you’’ve got to work hard, to make history, simple, you’’ve got to make it. Always remember in the jungle there’’s a lot of they in there, after you overcome they, you will make it to paradise. It’’s on you how you want to live your life. Everyone has a choice. I pick my choice, squeaky clean. In life there will be road blocks but we will over come it. Look at the sunset, life is amazing, life is beautiful, life is what you make it. The key is to drink coconut, fresh coconut, trust me.', 4, 2)
  ;
